# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Custom Watershed.py
# Created on: 2019-01-03 15:09:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Custom Watershed <Pour_Point> <Input_AOI_Lidar> <watershdshp> <Flow_Length_surface> <ShedSlope> <SlopeMean> 
# Description: 
# Place a point on Lidar elevation data to find all the upland area which flows to your selected point
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
        arcpy.CheckOutExtension("3D")
        arcpy.CheckOutExtension("Spatial")

        
# Script arguments
Pour_Point = arcpy.GetParameterAsText(0)
if Pour_Point == '#' or not Pour_Point:
    Pour_Point = "in_memory\\{343A487C-17A8-43F6-8CCB-1CCFEE3DB930}" # provide a default value if unspecified

Input_AOI_Lidar = arcpy.GetParameterAsText(1)

watershdshp = arcpy.GetParameterAsText(2)
if watershdshp == '#' or not watershdshp:
    watershdshp = "c:\\scratch\\Watershed.shp" # provide a default value if unspecified

Flow_Length_surface = arcpy.GetParameterAsText(3)
if Flow_Length_surface == '#' or not Flow_Length_surface:
    Flow_Length_surface = "c:\\scratch\\FlowLenMETERS" # provide a default value if unspecified

ShedSlope = arcpy.GetParameterAsText(4)
if ShedSlope == '#' or not ShedSlope:
    ShedSlope = "c:\\scratch\\Slope" # provide a default value if unspecified

SlopeMean = arcpy.GetParameterAsText(5)
if SlopeMean == '#' or not SlopeMean:
    SlopeMean = "c:\\scratch\\SlopeMean" # provide a default value if unspecified

# Local variables:
Fill_ = ""
fill_output = ""
FlowDir_Fill1 = ""
FlowAcc_Flow1 = ""
SnapPou_1 = "c:\\scratch\\SnapPou_1"
rasteroutput = ""
wtrshedinfo = watershdshp
Extract_fill2 = ""
watershedshp3 = wtrshedinfo
Watershed_Shape = watershedshp3
wshd = ""

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "c:\\scratch"
arcpy.env.workspace = "c:\\scratch"

# Process: Fill
arcpy.gp.Fill_sa(Input_AOI_Lidar, Fill_, "")

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(Fill_, FlowDir_Fill1, "NORMAL", fill_output)

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(FlowDir_Fill1, FlowAcc_Flow1, "", "FLOAT")

# Process: Snap Pour Point
arcpy.gp.SnapPourPoint_sa(Pour_Point, FlowAcc_Flow1, SnapPou_1, "15", "Id")

# Process: Watershed
arcpy.gp.Watershed_sa(FlowDir_Fill1, SnapPou_1, rasteroutput, "VALUE")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(rasteroutput, watershdshp, "SIMPLIFY", "")

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(FlowDir_Fill1, watershdshp, Extract_fill2)

# Process: Flow Length
arcpy.gp.FlowLength_sa(Extract_fill2, Flow_Length_surface, "UPSTREAM", "")

# Process: Add Surface Information
arcpy.AddSurfaceInformation_3d(watershdshp, Fill_, "Z_MIN;Z_MAX;SURFACE_AREA;MIN_SLOPE;MAX_SLOPE;AVG_SLOPE", "BILINEAR", "", "1", "0", "NO_FILTER")

# Process: Add Field
arcpy.AddField_management(wtrshedinfo, "Acres", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(watershedshp3, "Acres", "[SArea] /4046.86", "VB", "")

# Process: Extract by Mask (2)
arcpy.gp.ExtractByMask_sa(Input_AOI_Lidar, watershdshp, wshd)

# Process: Slope
arcpy.gp.Slope_sa(wshd, ShedSlope, "DEGREE", "1")

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(Watershed_Shape, "ID", ShedSlope, SlopeMean, "MEAN", "DATA")

